"""Embedding domain package: credential-free typed inputs, errors, and provider protocols."""

from .inputs import (
    TextEmbeddingInput,
    ImageEmbeddingInput,
    VideoEmbeddingInput,
    EmbeddingInput,
    EmbeddingModelSpec,
    EmbeddingBatch,
)
from .errors import (
    EmbeddingError,
    EMBEDDING_MODEL_NOT_CONFIGURED,
    EMBEDDING_MODEL_DISABLED,
    EMBEDDING_ADMIN_UNRESOLVED,
    EMBEDDING_ADMIN_AMBIGUOUS,
    EMBEDDING_CREDENTIALS_MISSING,
    EMBEDDING_PROVIDER_UNSUPPORTED,
    EMBEDDING_MODALITY_UNSUPPORTED,
    EMBEDDING_OUTPUT_COUNT_MISMATCH,
    EMBEDDING_VECTOR_NOT_SEQUENCE,
    EMBEDDING_VECTOR_VALUE_INVALID,
    EMBEDDING_VECTOR_NON_FINITE,
    EMBEDDING_DIMENSION_MISMATCH,
    EMBEDDING_PROVIDER_FAILED,
    EMBEDDING_IMAGE_FORMAT_UNSUPPORTED,
    EMBEDDING_IMAGE_INVALID,
    VIDEO_VALIDATION_FAILED,
    VIDEO_DURATION_EXCEEDED,
    PDF_VISUAL_EXTRACTION_FAILED,
    PDF_VISUAL_LIMIT_EXCEEDED,
    PDF_VISUALS_REQUIRE_MULTIMODAL_MODEL,
    safe_file_processing_error_code,
    safe_file_processing_error_message,
    safe_file_processing_warnings,
    EMBEDDING_MODEL_SPACE_MIXED,
    EMBEDDING_MODEL_STATE_CONFLICT,
    EMBEDDING_INVENTORY_UNRESOLVED_SOURCE,
    EMBEDDING_INVENTORY_AMBIGUOUS_SOURCE,
    EMBEDDING_INVENTORY_AMBIGUOUS_ADMIN,
    EMBEDDING_INVENTORY_MISSING_FILE,
    EMBEDDING_INVENTORY_MALFORMED_REFERENCE,
    EMBEDDING_JOB_ACTIVE_EXISTS,
    EMBEDDING_JOB_NOT_FOUND,
    EMBEDDING_JOB_TERMINAL,
    EMBEDDING_JOB_STALE_OPERATION,
    EMBEDDING_JOB_WRONG_STATUS,
    EMBEDDING_FILE_NOT_FOUND,
    EMBEDDING_FILE_WRONG_STATUS,
    EMBEDDING_REINDEX_NOT_READY,
    EMBEDDING_REINDEX_SOURCE_CHANGED,
    EMBEDDING_RETRY_ACTIVE_EXISTS,
)
from .provider import EmbeddingProvider, EmbeddingProviderFactory
from .state import (
    AdminEmbeddingModelStateView,
    AdminEmbeddingModelStateRepository,
)
from .gate import (
    RetrievalModelSpace,
    RetrievalReadyNoState,
    assert_embedding_retrieval_ready,
)
from .inventory import (
    ReindexFile,
    build_reindex_inventory,
    SOURCE_KNOWLEDGE,
    SOURCE_CHAT_UPLOAD,
)
from .jobs import (
    EmbeddingJobView,
    EmbeddingJobFileView,
    CreateJobResult,
    EmbeddingJobRepository,
    EmbeddingJobStatusView,
    SourceContextCounts,
    SOURCE_CONTEXT_KNOWLEDGE,
    SOURCE_CONTEXT_CHAT_UPLOAD,
    SOURCE_CONTEXT_BOTH,
    JOB_STATUS_QUEUED,
    JOB_STATUS_PROCESSING,
    JOB_STATUS_COMPLETED,
    JOB_STATUS_FAILED,
    JOB_STATUS_PARTIALLY_FAILED,
    FILE_STATUS_PENDING,
    FILE_STATUS_PROCESSING,
    FILE_STATUS_COMPLETED,
    FILE_STATUS_FAILED,
    FILE_STATUS_INCOMPATIBLE,
)
from .model_change import (
    ModelChangeResult,
    ModelChangeNoOp,
    request_model_change,
)
# Keep the worker out of package-level imports: it loads file_processor, which
# imports the retrieval router while that router is still initializing.
from .enqueue import (
    enqueue_embedding_job,
    EMBEDDING_REINDEX_QUEUE_NAME,
)

__all__ = [
    # Inputs
    "TextEmbeddingInput",
    "ImageEmbeddingInput",
    "VideoEmbeddingInput",
    "EmbeddingInput",
    "EmbeddingModelSpec",
    "EmbeddingBatch",
    # Errors
    "EmbeddingError",
    "EMBEDDING_MODEL_NOT_CONFIGURED",
    "EMBEDDING_MODEL_DISABLED",
    "EMBEDDING_ADMIN_UNRESOLVED",
    "EMBEDDING_ADMIN_AMBIGUOUS",
    "EMBEDDING_CREDENTIALS_MISSING",
    "EMBEDDING_PROVIDER_UNSUPPORTED",
    "EMBEDDING_MODALITY_UNSUPPORTED",
    "EMBEDDING_OUTPUT_COUNT_MISMATCH",
    "EMBEDDING_VECTOR_NOT_SEQUENCE",
    "EMBEDDING_VECTOR_VALUE_INVALID",
    "EMBEDDING_VECTOR_NON_FINITE",
    "EMBEDDING_DIMENSION_MISMATCH",
    "EMBEDDING_PROVIDER_FAILED",
    "EMBEDDING_IMAGE_FORMAT_UNSUPPORTED",
    "EMBEDDING_IMAGE_INVALID",
    "VIDEO_VALIDATION_FAILED",
    "VIDEO_DURATION_EXCEEDED",
    "PDF_VISUAL_EXTRACTION_FAILED",
    "PDF_VISUAL_LIMIT_EXCEEDED",
    "PDF_VISUALS_REQUIRE_MULTIMODAL_MODEL",
    "safe_file_processing_error_code",
    "safe_file_processing_error_message",
    "safe_file_processing_warnings",
    "EMBEDDING_MODEL_SPACE_MIXED",
    "EMBEDDING_MODEL_STATE_CONFLICT",
    "EMBEDDING_INVENTORY_UNRESOLVED_SOURCE",
    "EMBEDDING_INVENTORY_AMBIGUOUS_SOURCE",
    "EMBEDDING_INVENTORY_AMBIGUOUS_ADMIN",
    "EMBEDDING_INVENTORY_MISSING_FILE",
    "EMBEDDING_INVENTORY_MALFORMED_REFERENCE",
    "EMBEDDING_JOB_ACTIVE_EXISTS",
    "EMBEDDING_JOB_NOT_FOUND",
    "EMBEDDING_JOB_TERMINAL",
    "EMBEDDING_JOB_STALE_OPERATION",
    "EMBEDDING_JOB_WRONG_STATUS",
    "EMBEDDING_FILE_NOT_FOUND",
    "EMBEDDING_FILE_WRONG_STATUS",
    "EMBEDDING_REINDEX_NOT_READY",
    "EMBEDDING_REINDEX_SOURCE_CHANGED",
    "EMBEDDING_RETRY_ACTIVE_EXISTS",
    # Gate
    "RetrievalModelSpace",
    "RetrievalReadyNoState",
    "assert_embedding_retrieval_ready",
    # State
    "AdminEmbeddingModelStateView",
    "AdminEmbeddingModelStateRepository",
    # Inventory
    "ReindexFile",
    "build_reindex_inventory",
    "SOURCE_KNOWLEDGE",
    "SOURCE_CHAT_UPLOAD",
    # Protocols
    "EmbeddingProvider",
    "EmbeddingProviderFactory",
    # Jobs
    "EmbeddingJobView",
    "EmbeddingJobFileView",
    "CreateJobResult",
    "EmbeddingJobRepository",
    "EmbeddingJobStatusView",
    "SourceContextCounts",
    "SOURCE_CONTEXT_KNOWLEDGE",
    "SOURCE_CONTEXT_CHAT_UPLOAD",
    "SOURCE_CONTEXT_BOTH",
    "JOB_STATUS_QUEUED",
    "JOB_STATUS_PROCESSING",
    "JOB_STATUS_COMPLETED",
    "JOB_STATUS_FAILED",
    "JOB_STATUS_PARTIALLY_FAILED",
    "FILE_STATUS_PENDING",
    "FILE_STATUS_PROCESSING",
    "FILE_STATUS_COMPLETED",
    "FILE_STATUS_FAILED",
    "FILE_STATUS_INCOMPATIBLE",
    # Model Change
    "ModelChangeResult",
    "ModelChangeNoOp",
    "request_model_change",
    # Enqueue
    "enqueue_embedding_job",
    "EMBEDDING_REINDEX_QUEUE_NAME",
]
